version: "3.8"
services:
  mongo:
    image: mongo
    container_name: micromart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: micromart-auth
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth
      - JWT_KEY=SU93R$3CRETKEY
    depends_on:
      - mongo

  catalog:
    build:
      context: .
      dockerfile: services/catalog/Dockerfile
    container_name: micromart-catalog
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/catalog
      - JWT_KEY=SU93R$3CRETKEY
      - NATS_CLIENT_ID=catalog
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=micromart
    depends_on:
      - mongo
      - nats

  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    container_name: micromart-orders
    ports:
      - "3002:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/orders
      - JWT_KEY=SU93R$3CRETKEY
      - NATS_CLIENT_ID=orders
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=micromart
    depends_on:
      - mongo
      - nats

  nats:
    image: nats-streaming:0.17.0
    container_name: micromart-nats
    ports:
      - 4222:4222
      - 8222:8222
    command:
      [
        "-p",
        "4222",
        "-m",
        "8222",
        "-hbi",
        "5s",
        "-hbt",
        "5s",
        "-hbf",
        "2",
        "-SD",
        "-cid",
        "micromart",
      ]

  redis:
    image: redis:alpine
    container_name: micromart-redis

  expiration:
    build:
      context: .
      dockerfile: services/expiration/Dockerfile
    container_name: micromart-expiration
    environment:
      - NATS_CLIENT_ID=expiration
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=micromart
      - REDIS_HOST=redis
    depends_on:
      - nats
      - redis

  payments:
    build:
      context: .
      dockerfile: services/payments/Dockerfile
    container_name: micromart-payments
    ports:
      - "3003:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/payments
      - JWT_KEY=SU93R$3CRETKEY
      - NATS_CLIENT_ID=payments
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=micromart
      - STRIPE_KEY=${STRIPE_KEY}
    depends_on:
      - mongo
      - nats

  prometheus:
    image: prom/prometheus:latest
    container_name: micromart-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: micromart-grafana
    ports:
      - "3004:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  mongo_data:
